%int2stat converts integer to stat label
function statlabel = int2stat(int)
    stats = { 'team', '#', 'date', 'home', 'opp', 'win', 'min', 'fg', 'fga',...
            '3p', '3pa', 'ft', 'fta', 'orb', 'trb', 'ast', 'stl', 'blk', 'tov',...
            'pf', 'pts', 'OPPfg', 'OPPfga', 'OPP3p', 'OPP3pa', 'OPPft',...
            'OPPfta', 'OPPorb', 'OPPtrb', 'OPPast', 'OPPstl', 'OPPblk',...
            'OPPtov','OPPpf', 'OPPpts'};
    statlabel = stats(int);
