function outint = stat2int(input_str)
    stats = { 'team', '#', 'date', 'home', 'opp', 'win', 'min', 'fg', 'fga',...
        '3p', '3pa', 'ft', 'fta', 'orb', 'trb', 'ast', 'stl', 'blk', 'tov',...
        'pf', 'pts', 'OPPfg', 'OPPfga', 'OPP3p', 'OPP3pa', 'OPPft',...
        'OPPfta', 'OPPorb', 'OPPtrb', 'OPPast', 'OPPstl', 'OPPblk',...
        'OPPtov','OPPpf', 'OPPpts'};

    for i = 1:35
        if strcmp(input_str, stats(i))
            outint = i;
        end
    end
